spring:
  application:
    name: Authorization service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

app:
  jwt:
    secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uUHVycG9zZXM=
    expiration: 1800000  # 30 минут
    refresh-expiration: 86400000  # 24 часа
    init:
      roles: true

logging:
  charset:
    console: UTF-8
  level:
    root: WARN
    com.java.petrovsm.authorizationservice: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN